name: Process Artwork Submission

on:
  repository_dispatch:
    types: [artwork-submission]

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Process submission
        run: |
          echo '${{ toJSON(github.event.client_payload) }}' > submission.json
          node --experimental-modules .github/scripts/update-data.js
        
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/assets/data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Add new artwork submission"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
